# Temporary workaround for issue with rubygems 2.2.0 with bundler 1.5 on ruby
# 1.8.7.
#
# A fix has been merged to rubygems but not yet released. See:
# https://github.com/rubygems/rubygems/commit/f8e0f1d5f67cfc4e1966cc1e2db367aebf8a09e4
#
# See also CHEF-4916
#
# This workaround should be removed when that fix is released.
before_install:
  - sudo apt-get update
  - sudo apt-get install libgecode-dev
  - gem --version

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

script: 
  - bundle exec rake compile
  - bundle exec rake spec
